// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTv505TygSnnCaqb45g87XRo9HchItBJ8',
    appId: '1:207705978910:web:8970bdfb7f8ee14309560f',
    messagingSenderId: '207705978910',
    projectId: 'chatflutter-80bb1',
    authDomain: 'chatflutter-80bb1.firebaseapp.com',
    storageBucket: 'chatflutter-80bb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9f4bpeRmq_NcytKYtNoUS6RKL7XPmTE',
    appId: '1:207705978910:android:506bcffcae80eda709560f',
    messagingSenderId: '207705978910',
    projectId: 'chatflutter-80bb1',
    storageBucket: 'chatflutter-80bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjG-ThofU4O86LMOEqHkmGpMhqjFHrGjU',
    appId: '1:207705978910:ios:0f70524b7aef78de09560f',
    messagingSenderId: '207705978910',
    projectId: 'chatflutter-80bb1',
    storageBucket: 'chatflutter-80bb1.appspot.com',
    androidClientId: '207705978910-hvh6euoiqanhpdavi201vq5rtti13h5j.apps.googleusercontent.com',
    iosClientId: '207705978910-i7ennv0n0clbb08co6balg4k1tj7jh70.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjG-ThofU4O86LMOEqHkmGpMhqjFHrGjU',
    appId: '1:207705978910:ios:d087c6c5b3c5aae409560f',
    messagingSenderId: '207705978910',
    projectId: 'chatflutter-80bb1',
    storageBucket: 'chatflutter-80bb1.appspot.com',
    androidClientId: '207705978910-hvh6euoiqanhpdavi201vq5rtti13h5j.apps.googleusercontent.com',
    iosClientId: '207705978910-nf3m7ebthbhib4939tu5kvcgpagdkftk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
